### PR TITLE
Fix segfault on strftime

### LINKED ISSUE #130: Segmentation fault in src/faillog.c:167 print_one when reading corrupt /var/log/faillog file
Tested with Debian's `login=1:4.4-4.1` and the repositories master branch:
```
# xxd -r > /var/log/faillog << EOF
00000000: 3030 3030 3030 3030 3030 3030 3030 3030  0000000000000000
00000010: 3030 3030 3030 3030 3030 3030 3030 3030  0000000000000000
EOF
# faillog -a
Login       Failures Maximum Latest                   On

Segmentation fault
```
```
Invalid read of size 8
   at 0x4EE6961: __strftime_internal (strftime_l.c:533)
   by 0x4EE8A45: strftime_l (strftime_l.c:459)
   by 0x10A4D4: print_one (faillog.c:167)
   by 0x109B4D: print (faillog.c:207)
   by 0x109B4D: main (faillog.c:721)
 Address 0x30 is not stack'd, malloc'd or (recently) free'd


Process terminating with default action of signal 11 (SIGSEGV)
 Access not within mapped region at address 0x30
   at 0x4EE6961: __strftime_internal (strftime_l.c:533)
   by 0x4EE8A45: strftime_l (strftime_l.c:459)
   by 0x10A4D4: print_one (faillog.c:167)
   by 0x109B4D: print (faillog.c:207)
   by 0x109B4D: main (faillog.c:721)
```

### PR DESCRIPTION
**Pull request by edneville**
Drop out in faillog if time is unreadable.
Adding myself to contributors

Closes #130

### CODE REVIEW

File: src/faillog.c [hunk 1]
```diff
@@ -163,6 +163,10 @@ static void print_one (/*@null@*/const struct passwd *pw, bool force)
 	}
 
 	tm = localtime (&fl.fail_time);
+	if (!tm) {
+		fprintf (stderr, "Cannot read time from faillog.\n");
+		exit (EXIT_FAILURE);
```
Comment (hallyn) [inline src/faillog.c]: Thank you for the patch.  However, in keeping with the rest of this function it would be better to return rather than exit.  Could you update the patch to do that?

**Comment by edneville** [comment]
@hallyn I've added a commit which replaces the exit with return. Thanks to reviewing.
