### PR TITLE
Bugfix: useradd: fix btrfs subvolume home creation

### LINKED ISSUE #1616: -d /not-under-home and --btrfs-subvolume-home flag are incompatible
For some reason creating a home dir outside of /home ignores the BTRFS Subvolume creation that got requested.

### PR DESCRIPTION
**Pull request by silverhadch**
dirname() replaces broken stpcpy index arithmetic that produced an empty string for single-component paths, causing statfs to fail and fall back to a regular directory. Gate subvolume creation on user_id >= UID_MIN to exclude system users regardless of their home path.

Closes #1616

### CODE REVIEW

**Comment by silverhadch** [comment]
@alejandro-colomar 
CC: @Conan-Kudo

File: src/useradd.c [hunk 1]
```diff
@@ -2264,7 +2271,8 @@ static void create_home(const struct option_flags *flags)
 
 		dir_created = false;
 #if WITH_BTRFS
-		if (subvolflg && (strlen(prefix_user_home) - (int)strlen(path)) <= 1) {
+		if (subvolflg && user_id >= uid_min
+		    && (strlen(prefix_user_home) - (int)strlen(path)) <= 1) {
```
Comment (alejandro-colomar) [inline src/useradd.c]: The `user_id >= uid_min` change seems completely unrelated to the dirname(3) one.  Please keep logically unrelated changes in separate commits.

Comment (alejandro-colomar) [reply src/useradd.c]: Also, if this fixes issues, please add appropriate `Fixes:` tags for the commits that introduced the issues.

File: src/useradd.c [hunk 2]
```diff
@@ -2274,10 +2282,10 @@ static void create_home(const struct option_flags *flags)
 					Prog, path);
 				fail_exit(E_HOMEDIR, process_selinux);
 			}
-			stpcpy(&btrfs_check[strlen(path) - strlen(cp) - 1], "");
-			if (statfs(btrfs_check, &sfs) == -1) {
+			if (statfs(dirname(btrfs_check), &sfs) == -1) {
 				fprintf(stderr, "%s: statfs(\"%s\"): %s\n",
-					Prog, btrfs_check, strerrno());
+					Prog, path, strerrno());
+				free(btrfs_check);
```
Comment (alejandro-colomar) [inline src/useradd.c]: Why is `path` used in the log?  I don't understand that change.

Comment (silverhadch) [reply src/useradd.c]: btrfs_check no longer contains the original path as it's been truncated to the parent. path is the actual home dir we were trying to operate on, which is more useful in the error.

Comment (alejandro-colomar) [reply src/useradd.c]: Then the format string should be changed to `"%s: statfs(dirname(\"%s\")): %s\n"`

Comment (alejandro-colomar) [inline src/useradd.c]: Why is this free(3) being added here?  This is not documented in the commit message!

Comment (silverhadch) [reply src/useradd.c]: Sorry will split it into a fix leak commit.

Comment (alejandro-colomar) [reply src/useradd.c]: But this is not a leak.  exit(3) is defined to free(3) all memory.

File: src/useradd.c [hunk 3]
```diff
@@ -2264,7 +2271,8 @@ static void create_home(const struct option_flags *flags)
 
 		dir_created = false;
 #if WITH_BTRFS
-		if (subvolflg && (strlen(prefix_user_home) - (int)strlen(path)) <= 1) {
+		if (subvolflg && user_id >= uid_min
+			&& (strlen(prefix_user_home) - (int)strlen(path)) <= 1) {
```
Comment (alejandro-colomar) [inline src/useradd.c]: Should we also take `UID_MAX` into consideration?

```
$ man login.defs | awk '/^ {5}UID_/,/^$/'
     UID_MAX (number), UID_MIN (number)
         Range of user IDs used for the creation of regular users by useradd or
         newusers.

```

File: src/useradd.c (hunk 2 above)
Comment (silverhadch) [reply src/useradd.c]: oh didnt take a closer look. Forget it.

File: src/useradd.c (hunk 3 above)
Comment (silverhadch) [reply src/useradd.c]: Done.

File: src/useradd.c [hunk 4]
```diff
@@ -2284,10 +2284,9 @@ static void create_home(const struct option_flags *flags)
 					Prog, path);
 				fail_exit(E_HOMEDIR, process_selinux);
 			}
-			stpcpy(&btrfs_check[strlen(path) - strlen(cp) - 1], "");
-			if (statfs(btrfs_check, &sfs) == -1) {
-				fprintf(stderr, "%s: statfs(\"%s\"): %s\n",
-					Prog, btrfs_check, strerrno());
+			if (statfs(dirname(btrfs_check), &sfs) == -1) {
+				fprintf(stderr, "%s: statfs(dirname(\"%s\")): %s\n",
+					Prog, path, strerrno());
```
Comment (alejandro-colomar) [inline src/useradd.c:2279]: For commit 2 ("useradd: fix btrfs subvolume creation for single-component basedir"):

```
Reviewed-by: Alejandro Colomar <alx@kernel.org>
```

File: src/useradd.c [hunk 5]
```diff
@@ -2264,7 +2273,8 @@ static void create_home(const struct option_flags *flags)
 
 		dir_created = false;
 #if WITH_BTRFS
-		if (subvolflg && (strlen(prefix_user_home) - (int)strlen(path)) <= 1) {
+		if (subvolflg && user_id >= uid_min && user_id <= uid_max
+			&& (strlen(prefix_user_home) - (int)strlen(path)) <= 1) {
```
Comment (alejandro-colomar) [inline src/useradd.c]: Please move the `{` to the next line.  See the braces guidelines here:
<https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/tree/CONTRIBUTING.d/style/c#n46>.

```
	Use K&R style for braces.  But if the controlling expression of
	an if/for/while is broken, the opening brace goes on a line of
	its own.

		if (foo)
			bar();

		if (foooooooooooooooooooooooooo
		 || baaaaaaaaaaaaaaaaaaaaaaaaaar)
		{
			baz();
		}
```

**Comment by alejandro-colomar** [comment]
CI seems to be consistently failing some test.  Could you please check why?

Cc: @ikerexxe

**Comment by alejandro-colomar** [comment]
> CI seems to be consistently failing some test. Could you please check why?
> 
> Cc: @ikerexxe

I think this is the relevant part of the log:

```sh

2026-04-28T11:36:21.4888039Z ##[group]Run set -e
2026-04-28T11:36:21.4888283Z [36;1mset -e[0m
2026-04-28T11:36:21.4888453Z [36;1mcd tests[0m
2026-04-28T11:36:21.4888640Z [36;1mtrap 'cat testsuite.log' ERR[0m
2026-04-28T11:36:21.4888877Z [36;1msudo ./run_some[0m
2026-04-28T11:36:21.4889073Z [36;1mtrap - ERR[0m
2026-04-28T11:36:21.4932368Z shell: /usr/bin/script -q -e -c "bash {0}"
2026-04-28T11:36:21.4932644Z ##[endgroup]
2026-04-28T11:36:21.5270783Z +: test passed
2026-04-28T11:36:21.5271211Z -: test failed
2026-04-28T11:36:49.2061345Z .+-++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2026-04-28T11:36:49.2061933Z 75 test(s) passed
2026-04-28T11:36:49.2062237Z 1 test(s) failed
2026-04-28T11:36:49.2062542Z log written in 'testsuite.log'
2026-04-28T11:36:49.2062908Z the following tests failed:
2026-04-28T11:36:49.2063248Z  ./su/01/su_root.test
2026-04-28T11:36:49.2084657Z 
2026-04-28T11:36:49.2085118Z ###############################################################################
2026-04-28T11:36:49.2085883Z #
2026-04-28T11:36:49.2086171Z # Test: ./su/01/su_user.test
2026-04-28T11:36:49.2086518Z #
2026-04-28T11:36:49.2086860Z ###############################################################################
2026-04-28T11:36:49.2092574Z #
2026-04-28T11:36:49.2093076Z # Rationale: su can be used to switch to a non-root user
2026-04-28T11:36:49.2093640Z #
2026-04-28T11:36:49.2094014Z ###############################################################################
2026-04-28T11:36:49.2094721Z # switch to the passwordless 'testsuite' user
2026-04-28T11:36:49.2095354Z # and expect a '$ ' prompt
2026-04-28T11:36:49.2095833Z spawn /bin/su testsuite
2026-04-28T11:36:49.2096082Z 
2026-04-28T11:36:49.2096089Z 
2026-04-28T11:36:49.2096219Z FAIL (timeout)
2026-04-28T11:36:49.2096620Z ###############################################################################
2026-04-28T11:36:49.2097674Z #
2026-04-28T11:36:49.2098525Z # Status of test ./su/01/su_user.test: FAILURE
2026-04-28T11:36:49.2099111Z #
2026-04-28T11:36:49.2099537Z ###############################################################################
2026-04-28T11:36:49.2100033Z 
2026-04-28T11:36:49.2100234Z ###############################################################################
2026-04-28T11:36:49.2100740Z #
2026-04-28T11:36:49.2100982Z # Test: ./su/01/su_user.test
2026-04-28T11:36:49.2101289Z #
2026-04-28T11:36:49.2101576Z ###############################################################################
2026-04-28T11:36:49.2101991Z #
2026-04-28T11:36:49.2102313Z # Rationale: su can be used to switch to a non-root user
2026-04-28T11:36:49.2102761Z #
2026-04-28T11:36:49.2103049Z ###############################################################################
2026-04-28T11:36:49.2103533Z # switch to the passwordless 'testsuite' user
2026-04-28T11:36:49.2103962Z # and expect a '$ ' prompt
2026-04-28T11:36:49.2104294Z spawn /bin/su testsuite
2026-04-28T11:36:49.2104499Z 
2026-04-28T11:36:49.2104661Z groups: cannot find name for group ID 424243
2026-04-28T11:36:49.2104962Z 
2026-04-28T11:36:49.2105239Z testsuite@runnervmrc6n4:~/runner/work/shadow/shadow/tests/su/01$ 
2026-04-28T11:36:49.2105789Z # make sure we are now 'testsuite'
2026-04-28T11:36:49.2106285Z # id should return 'uid=424243(testsuite) gid=424243 groups=424243'
2026-04-28T11:36:49.2106694Z 
2026-04-28T11:36:49.2106971Z testsuite@runnervmrc6n4:~/runner/work/shadow/shadow/tests/su/01$ id
2026-04-28T11:36:49.2107752Z 
2026-04-28T11:36:49.2107911Z uid=424243(testsuite) gid=424243 groups=424243
2026-04-28T11:36:49.2108221Z 
2026-04-28T11:36:49.2108491Z testsuite@runnervmrc6n4:~/runner/work/shadow/shadow/tests/su/01$ 
2026-04-28T11:36:49.2108909Z 
2026-04-28T11:36:49.2109033Z # now switch to user 'myuser'
2026-04-28T11:36:49.2109478Z # and expect a password prompt
2026-04-28T11:36:49.2109735Z 
2026-04-28T11:36:49.2110056Z testsuite@runnervmrc6n4:~/runner/work/shadow/shadow/tests/su/01$ su myuser
2026-04-28T11:36:49.2110589Z 
2026-04-28T11:36:49.2110695Z Password: 
2026-04-28T11:36:49.2111259Z # password 'myuserF00barbaz' sent
2026-04-28T11:36:49.2111536Z 
2026-04-28T11:36:49.2111656Z # expect prompt '$ '
2026-04-28T11:36:49.2111852Z 
2026-04-28T11:36:49.2112102Z myuser@runnervmrc6n4:~/runner/work/shadow/shadow/tests/su/01$ 
2026-04-28T11:36:49.2112507Z 
2026-04-28T11:36:49.2112623Z # make sure we are 'myuser'
2026-04-28T11:36:49.2112992Z # id should return '(myuser).*(myuser).*(myuser)
2026-04-28T11:36:49.2113294Z 
2026-04-28T11:36:49.2113552Z myuser@runnervmrc6n4:~/runner/work/shadow/shadow/tests/su/01$ id
2026-04-28T11:36:49.2113961Z 
2026-04-28T11:36:49.2114166Z uid=424242(myuser) gid=424242(myuser) groups=424242(myuser)
2026-04-28T11:36:49.2114401Z 
2026-04-28T11:36:49.2114569Z myuser@runnervmrc6n4:~/runner/work/shadow/shadow/tests/su/01$ exit
2026-04-28T11:36:49.2114818Z 
2026-04-28T11:36:49.2114873Z exit
2026-04-28T11:36:49.2114958Z 
```

File: src/useradd.c [hunk 6]
```diff
@@ -2220,12 +2220,21 @@ static void create_home(const struct option_flags *flags)
...
 	process_selinux = !flags->chroot && !flags->prefix;
 
 	if (access (prefix_user_home, F_OK) == 0)
 		return;
 
+#if WITH_BTRFS
+	uid_min = getdef_ulong("UID_MIN", 1000UL);
+	uid_max = getdef_ulong("UID_MAX", 60000UL);
+#endif
+
```
Comment (alejandro-colomar) [inline src/useradd.c]: Could you please separate the two commits into two separate PRs?  That would help find out which of the two commits is failing CI.  Since the two changes are completely unrelated, it's fine to split them into separate PRs.

Comment (silverhadch) [reply src/useradd.c]: Split one commit off into https://github.com/shadow-maint/shadow/pull/1619

Comment (silverhadch) [reply src/useradd.c]: Both commits seem to trigger a failing pipeline so they seem unrelated.

Comment (alejandro-colomar) [reply src/useradd.c]: The opensuse one doesn't worry me; that's a common one.  However, the other one was worrying.  However, it seems to have vanished now, so maybe it was just random.

**Review by alejandro-colomar — APPROVED** [review]
It seems the CI error has vanished (ignoring the opensuse one, which is common, and known).

Thanks!
