### PR TITLE
Restore the original terminal pgrp after editing

### LINKED ISSUE #1194: vipw/vigr affect bash because it changes to PGID.
To fix vipw/vigr not resuming when suspended, the following commit had been added to change pgid(ie. pgrp)

[Fix vipw not resuming correctly when suspended](https://github.com/shadow-maint/shadow/commit/7eca1112fbd7a3eae6a6cbc6e52482a0a8326ff7)

However, vipw/vigr changes to bash's PGID, which affect bash.

```
[root@rhel9 ~]# ps axo stat,euid,ruid,tty,tpgid,sess,pgrp,ppid,pid,pcpu,comm
STAT  EUID  RUID TT         TPGID    SESS    PGRP    PPID     PID %CPU COMMAND 
__snip__
Ss       0     0 pts/2      10607    4070    4070    3571    4070  0.0 bash
S        0     0 pts/2      10607    4070    4070    4070   10606  0.0 vipw
S+       0     0 pts/2      10607    4070   10607   10606   10607  0.0 vipw
S+       0     0 pts/2      10607    4070   10607   10607   10608  0.1 vim
```

# Steps to reproduce

## Problem#1
1. Disable monitor-mode in bash.

  `# set +m
  ` 

2. Run vipw or vigr 

  `# vipw
  `

After exiting the editor, bash exists on its own.

```
[root@rhel9 ~]# strace -ffvv -p $bash_pid
__snip__
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 10606
__snip__
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
setpgid(0, 10658)                       = -1 EPERM (Operation not permitted)
exit_group(0)                           = ?
+++ exited with 0 +++
```

## Problem#2

1. Create the following script file:
 
```test.sh
#!/bin/bash
/usr/sbin/vipw
echo Enter any key
read -s
 ```

2. Run the script
 
```
[root@rhel9 ~]# chmod +x test.sh
[root@rhel9 ~]# ./test.sh
```

The script stops by SIGTTOU.
 
```
[root@rhel9 ~]# ./test.sh 
vipw: /etc/passwd is unchanged
Enter any key

[1]+  Stopped                 ./test.sh
[root@rhel9 ~]# jobs -l
[1]+ 61799 Stopped (tty output)    ./test.sh
```

### PR DESCRIPTION
**Pull request by millert**
This fixes a problem when the shell is not in monitor mode (job control enabled) which resulted in the terminal pgrp being set to an invalid value once vipw exited.  Fixes #1194.

### CODE REVIEW

File: src/vipw.c [hunk 1]
```diff
@@ -372,8 +372,14 @@ vipwedit (const char *file, int (*file_lock) (void), int (*file_unlock) (void))
...
 
-	if (orig_pgrp != -1)
+	if (orig_pgrp != -1) {
+		 /* Restore terminal pgrp after editing. */
+		if (tcsetpgrp(STDIN_FILENO, orig_pgrp) == -1) {
+			fprintf (stderr, "%s: %s: %s", Prog,
+				 "tcsetpgrp", strerror (errno));
+		}
 		sigprocmask(SIG_SETMASK, &omask, NULL);
+	}
```
Comment (alejandro-colomar) [inline src/vipw.c:382]:
```
Reviewed-by: Alejandro Colomar <alx@kernel.org>
Tested-by: Alejandro Colomar <alx@kernel.org>
```

```sh
alx@devuan:/srv/alx/src/shadow/shadow/master$ sudo bash
[sudo] password for alx: 
root@devuan:/srv/alx/src/shadow/shadow/master# set +m
root@devuan:/srv/alx/src/shadow/shadow/master# ./src/vipw
vipw: /etc/passwd is unchanged
root@devuan:/srv/alx/src/shadow/shadow/master# 
root@devuan:/srv/alx/src/shadow/shadow/master# exit
exit
```

**Review by alejandro-colomar — APPROVED** [review]
```
Tested-by: Alejandro Colomar <alx@kernel.org>
Reviewed-by: Alejandro Colomar <alx@kernel.org>
```

```sh
alx@devuan:/srv/alx/src/shadow/shadow/master$ sudo bash
[sudo] password for alx: 
root@devuan:/srv/alx/src/shadow/shadow/master# set +m
root@devuan:/srv/alx/src/shadow/shadow/master# ./src/vipw
vipw: /etc/passwd is unchanged
root@devuan:/srv/alx/src/shadow/shadow/master# 
root@devuan:/srv/alx/src/shadow/shadow/master# exit
exit
```

Thanks!

**Comment by alejandro-colomar** [comment]
I've applied some amendments to the commit (commit message formatting, and also removal of white space in source code):

```
$ git range-diff mt/master mt/pgrp_fix pgrp_fix 
1:  d61b626c ! 1:  7dcb9a0a Restore the original terminal pgrp after editing
    @@ Metadata
     Author: Todd C. Miller <Todd.Miller@sudo.ws>
     
      ## Commit message ##
    -    Restore the original terminal pgrp after editing
    +    src/vipw.c: Restore the original terminal pgrp after editing
     
         This fixes a problem when the shell is not in monitor mode (job control
         enabled) which resulted in the terminal pgrp being set to an invalid
    -    value once vipw exited.  Fixes #1194.
    +    value once vipw exited.
    +
    +    Fixes: 7eca1112fbd7 (2019-11-11; "Fix vipw not resuming correctly when suspended")
    +    Closes: <https://github.com/shadow-maint/shadow/issues/1194>
    +    Reported-by: <https://github.com/yonecle>
    +    Tested-by: Alejandro Colomar <alx@kernel.org>
    +    Reviewed-by: Alejandro Colomar <alx@kernel.org>
     
      ## src/vipw.c ##
     @@ src/vipw.c: vipwedit (const char *file, int (*file_lock) (void), int (*file_unlock) (void))
    @@ src/vipw.c: vipwedit (const char *file, int (*file_lock) (void), int (*file_unlo
     +  if (orig_pgrp != -1) {
     +           /* Restore terminal pgrp after editing. */
     +          if (tcsetpgrp(STDIN_FILENO, orig_pgrp) == -1) {
    -+                  fprintf (stderr, "%s: %s: %s", Prog,
    -+                           "tcsetpgrp", strerror (errno));
    ++                  fprintf(stderr, "%s: %s: %s", Prog,
    ++                          "tcsetpgrp", strerror(errno));
     +          }
                sigprocmask(SIG_SETMASK, &omask, NULL);
     +  }
```

**Comment by alejandro-colomar** [comment]
Cc: @yonecle

**Comment by alejandro-colomar** [comment]
Since nobody else has commented, and the experiment seems to confirm this is good, I'll merge now.  Thanks!
